define(["require", "exports", "./../../../src/check-box/index", "@syncfusion/ej2-base"], function (require, exports, index_1, ej2_base_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    ej2_base_1.enableRipple(true);
    var cbox1 = new index_1.CheckBox({ label: 'Default' });
    cbox1.appendTo('#checkbox1');
    var cbox2 = new index_1.CheckBox({ label: 'Default', checked: true });
    cbox2.appendTo('#checkbox2');
    var cbox3 = new index_1.CheckBox({ label: 'Default', indeterminate: true });
    cbox3.appendTo('#checkbox3');
    var cbox4 = new index_1.CheckBox({ label: 'Small', cssClass: 'e-small' });
    cbox4.appendTo('#checkbox4');
    var cbox5 = new index_1.CheckBox({ label: 'Small', checked: true, cssClass: 'e-small' });
    cbox5.appendTo('#checkbox5');
    var cbox6 = new index_1.CheckBox({ label: 'Small', indeterminate: true, cssClass: 'e-small' });
    cbox6.appendTo('#checkbox6');
    var cbox7 = new index_1.CheckBox({ label: 'Bigger', cssClass: 'e-bigger' });
    cbox7.appendTo('#checkbox7');
    var cbox8 = new index_1.CheckBox({ label: 'Bigger', checked: true, cssClass: 'e-bigger' });
    cbox8.appendTo('#checkbox8');
    var cbox9 = new index_1.CheckBox({ label: 'Bigger', indeterminate: true, cssClass: 'e-bigger' });
    cbox9.appendTo('#checkbox9');
    var cbox10 = new index_1.CheckBox({ label: 'Bigger_Small', cssClass: 'e-bigger e-small' });
    cbox10.appendTo('#checkbox10');
    var cbox11 = new index_1.CheckBox({ label: 'Bigger_Small', checked: true, cssClass: 'e-bigger e-small' });
    cbox11.appendTo('#checkbox11');
    var cbox12 = new index_1.CheckBox({ label: 'Bigger_Small', indeterminate: true, cssClass: 'e-bigger e-small' });
    cbox12.appendTo('#checkbox12');
});
