define(["require", "exports", "./../../../src/switch/index", "@syncfusion/ej2-base"], function (require, exports, index_1, ej2_base_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    ej2_base_1.enableRipple(true);
    var cbox1 = new index_1.Switch({});
    cbox1.appendTo('#switch1');
    var cbox2 = new index_1.Switch({ checked: true });
    cbox2.appendTo('#switch2');
    var cbox3 = new index_1.Switch({});
    cbox3.appendTo('#switch3');
    var cbox4 = new index_1.Switch({ cssClass: 'e-small' });
    cbox4.appendTo('#switch4');
    var cbox5 = new index_1.Switch({ checked: true, cssClass: 'e-small' });
    cbox5.appendTo('#switch5');
    var cbox6 = new index_1.Switch({ cssClass: 'e-small' });
    cbox6.appendTo('#switch6');
    var cbox7 = new index_1.Switch({ cssClass: 'e-bigger' });
    cbox7.appendTo('#switch7');
    var cbox8 = new index_1.Switch({ checked: true, cssClass: 'e-bigger' });
    cbox8.appendTo('#switch8');
    var cbox9 = new index_1.Switch({ cssClass: 'e-bigger' });
    cbox9.appendTo('#switch9');
    var cbox10 = new index_1.Switch({ cssClass: 'e-bigger e-small' });
    cbox10.appendTo('#switch10');
    var cbox11 = new index_1.Switch({ checked: true, cssClass: 'e-bigger e-small' });
    cbox11.appendTo('#switch11');
    var cbox12 = new index_1.Switch({ cssClass: 'e-bigger e-small' });
    cbox12.appendTo('#switch12');
});
