define(["require", "exports", "./../../../src/radio-button/index", "@syncfusion/ej2-base"], function (require, exports, index_1, ej2_base_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    ej2_base_1.enableRipple(true);
    var radiobutton = new index_1.RadioButton({ label: 'Male', name: 'gender-demo1', value: 'male', checked: true });
    radiobutton.appendTo('#radio1');
    radiobutton = new index_1.RadioButton({ label: 'Female', name: 'gender-demo1', value: 'female' });
    radiobutton.appendTo('#radio2');
    radiobutton = new index_1.RadioButton({ label: 'Others', name: 'gender-demo1', value: 'others', disabled: true });
    radiobutton.appendTo('#radio3');
    radiobutton = new index_1.RadioButton({ label: 'Male', name: 'gender-demo2', value: 'male', cssClass: 'e-small' });
    radiobutton.appendTo('#radio4');
    radiobutton = new index_1.RadioButton({ label: 'Female', name: 'gender-demo2', value: 'female', cssClass: 'e-small', checked: true });
    radiobutton.appendTo('#radio5');
    radiobutton = new index_1.RadioButton({ label: 'Others', name: 'gender-demo2', value: 'others', cssClass: 'e-small', disabled: true });
    radiobutton.appendTo('#radio6');
    radiobutton = new index_1.RadioButton({ label: 'Male', name: 'gender-demo3', value: 'male' });
    radiobutton.appendTo('#radio7');
    radiobutton = new index_1.RadioButton({ label: 'Female', name: 'gender-demo3', value: 'female' });
    radiobutton.appendTo('#radio8');
    radiobutton = new index_1.RadioButton({ label: 'Disabled', name: 'gender-demo3', value: 'others', checked: true, disabled: true });
    radiobutton.appendTo('#radio9');
    radiobutton = new index_1.RadioButton({ label: 'Male', name: 'gender-demo4', value: 'male', cssClass: 'e-small', checked: true });
    radiobutton.appendTo('#radio10');
    radiobutton = new index_1.RadioButton({ label: 'Female', name: 'gender-demo4', value: 'female', cssClass: 'e-small' });
    radiobutton.appendTo('#radio11');
    radiobutton = new index_1.RadioButton({ label: 'Others', name: 'gender-demo4', value: 'others', cssClass: 'e-small', disabled: true });
    radiobutton.appendTo('#radio12');
});
